### ISSUE TITLE
Issue with submodules

### ISSUE THREAD

**Issue by cjgarcia1984** [714Lemons/gpt-commit-generator#1]
The extension is generating commit messages, however when I use submodules it generates one message for the main module and submodules, instead of generating them separately since they are separate repos.

**Comment by 714Lemons** [comment]
Thx for finding it.

So there is currently no good way to get the Uri of the different scm/title buttons. However i managed to get the different repos that are open in the source control. That allows me to iterate over them and create different commit messages for each one. The main downside is that a message is created for every repo and you can not select a specific one.

For now i will close this issue. If you have a better solution for the problem feel free to contribute.
